'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSoperaciones
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://localhost:44393/MyProject/WebService1.asmx", ConfigurationName:="WSoperaciones.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Suma", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Suma(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Suma", ReplyAction:="*")>  _
        Function SumaAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Resta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Resta(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Division", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Division(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Division", ReplyAction:="*")>  _
        Function DivisionAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Multiplicacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Multiplicacion(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://localhost:44393/MyProject/WebService1.asmx/Multiplicacion", ReplyAction:="*")>  _
        Function MultiplicacionAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits WSoperaciones.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of WSoperaciones.WebService1Soap)
        Implements WSoperaciones.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Suma(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double Implements WSoperaciones.WebService1Soap.Suma
            Return MyBase.Channel.Suma(Numero1, Numero2)
        End Function
        
        Public Function SumaAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double) Implements WSoperaciones.WebService1Soap.SumaAsync
            Return MyBase.Channel.SumaAsync(Numero1, Numero2)
        End Function
        
        Public Function Resta(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double Implements WSoperaciones.WebService1Soap.Resta
            Return MyBase.Channel.Resta(Numero1, Numero2)
        End Function
        
        Public Function RestaAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double) Implements WSoperaciones.WebService1Soap.RestaAsync
            Return MyBase.Channel.RestaAsync(Numero1, Numero2)
        End Function
        
        Public Function Division(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double Implements WSoperaciones.WebService1Soap.Division
            Return MyBase.Channel.Division(Numero1, Numero2)
        End Function
        
        Public Function DivisionAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double) Implements WSoperaciones.WebService1Soap.DivisionAsync
            Return MyBase.Channel.DivisionAsync(Numero1, Numero2)
        End Function
        
        Public Function Multiplicacion(ByVal Numero1 As Double, ByVal Numero2 As Double) As Double Implements WSoperaciones.WebService1Soap.Multiplicacion
            Return MyBase.Channel.Multiplicacion(Numero1, Numero2)
        End Function
        
        Public Function MultiplicacionAsync(ByVal Numero1 As Double, ByVal Numero2 As Double) As System.Threading.Tasks.Task(Of Double) Implements WSoperaciones.WebService1Soap.MultiplicacionAsync
            Return MyBase.Channel.MultiplicacionAsync(Numero1, Numero2)
        End Function
    End Class
End Namespace
